complete --command gojq --exclusive -l arg -d "set variable to string value"
complete --command gojq --exclusive -l argjson -d "set variable to JSON value"
complete --command gojq --exclusive -l args -d "consume remaining arguments as positional string values"
complete --command gojq --exclusive -l color-output -s C -d "colorize output even if piped"
complete --command gojq --exclusive -l compact-output -s c -d "compact output"
complete --command gojq --exclusive -l exit-status -s e -d "exit 1 when the last value is false or null"
complete --command gojq --exclusive -l from-file -s f -d "load query from file"
complete --command gojq --exclusive -l help -s h -d "print help"
complete --command gojq --exclusive -l indent -d "number of spaces for indentation"
complete --command gojq --exclusive -l join-output -s j -d "stop printing a newline after each output"
complete --command gojq --exclusive -l jsonargs -d "consume remaining arguments as positional JSON values"
complete --command gojq --exclusive -l monochrome-output -s M -d "stop colorizing output"
complete --command gojq --exclusive -l nul-output -s 0 -d "print NUL after each output"
complete --command gojq --exclusive -l null-input -s n -d "use null as input value"
complete --command gojq --exclusive -l raw-input -s R -d "read input as raw strings"
complete --command gojq --exclusive -l raw-output -s r -d "output raw strings"
complete --command gojq --exclusive -l rawfile -d "set variable to the contents of the file"
complete --command gojq --exclusive -l slurp -s s -d "read all inputs into an array"
complete --command gojq --exclusive -l slurpfile -d "set variable to the JSON contents of the file"
complete --command gojq --exclusive -l stream -d "parse input in stream fashion"
complete --command gojq --exclusive -l tab -d "use tabs for indentation"
complete --command gojq --exclusive -l version -s v -d "print version"
complete --command gojq --exclusive -l yaml-input -d "read input as YAML"
complete --command gojq --exclusive -l yaml-output -d "output by YAML"
complete --command gojq --exclusive -s L -d "directory to search modules from"
